=== Chhuanga/Christ-University/MCA Trimester 1/Web Stack/demo/farmingDefinition.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT farm (crop+)>
<!ELEMENT crop (name,plantingDate,harvestingDate,quantity,unit)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT plantingDate (#PCDATA)>
<!ELEMENT harvestingDate (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit (#PCDATA)>

<!ATTLIST crop id ID #REQUIRED>
<!ATTLIST crop plant (veg|fruit|veggi) "veg">

=== Chhuanga/Christ-University/MCA Trimester 1/Web Stack/demo/farming.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE farm SYSTEM "farmingDefinition.dtd">
<farm>
    <crop id="C1" plant="veg">
        <name>Rice</name>
        <plantingDate>2024-08-15</plantingDate>
        <harvestingDate>2025-01-06</harvestingDate>
        <quantity>3000</quantity>
        <unit>kg</unit>
        </crop>
        <crop id="C2" plant="fruit">
            <name>Rice</name>
            <plantingDate>2024-08-15</plantingDate>
            <harvestingDate>2025-01-06</harvestingDate>
            <quantity>3000</quantity>
            <unit>kg</unit>
    </crop>
</farm>
